config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # == Devise Routes
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }

  # == Custom routes
  root to: "users#home"
  get "/landing" => "users#landing"
  get "/users" => "users#index"
  get "/bars" => "bars#index"
  get "/neighborhoods" => "neighborhoods#index"
  get "/user_reports/:id" => "users#user_reports"
  get "/find_bar" => "bars#find_bar"
  get "/check_user/:id" => "users#check_user"

  # == Admin Routes
  get "/admin" => "admins#home"
  get "/admin_landing" => "admins#admin_landing"
  get "/admin/users/:id" => "admins#admin_user"
  get "/admin_reports" => "reports#index"

  # == Google Bars
  get "/local_bars_json" => "bars#local_bars_json"

  # == RESTful Routes
  resources :users do
      resources :reports
  end
  resources :bars
  resources :neighborhoods
  resources :photos
  resources :tags
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/admin_landing.html.erb
<div id="landing_info">
    <% if @admin.firstname || @admin.lastname != nil %>
        <p>Welcome Back <%= @admin.firstname %> <%= @admin.lastname %></p>
        <p>Here's what new</p>
    <% end %>
</div>

app/views/admins/admin_user.html.erb
<!-- ====== views/admins/admin_user.html.erb ====== -->
<!-- ====== views/admins/admin_user.html.erb ====== -->
<!-- ====== views/admins/admin_user.html.erb ====== -->

<p id="notice"><%= notice %></p>

<h1><%= @users.fname %> <%= @users.lname %>'s Profile</h1>
<h2>Admin is looking at this</h2>

<!-- ======= ======= ======= USER PROFILE CONTAINER ======= ======= =======-->
<div id="user-profile-container" class="user-profile">
    <!-- ======= ======= USER PROFILE PIC ======= ======= -->
    <div id="user-profile-pic">
        <!-- <%#= image_tag(@photo.id.image.url) %> -->
    </div>

    <!-- ======= ======= USER BASIC INFO BOX ======= ======= -->
    <div id="user-profile-info">
        <!-- ====== USER FIRST NAME ======= -->
        <div id="user-info-fname" class="user-info">
            <p> First Name: <br><%= @users.fname %></p>
        </div>

        <!-- ====== USER LAST NAME ======= -->
        <div id="user-info-lname" class="user-info">
            <p> Last Name: <br><%= @users.lname %></p>
        </div>

        <!-- ====== USER USERNAME ======= -->
        <div id="user-info-username" class="user-info">
            <p> Username: <br><%= @users.username %></p>
        </div>

        <!-- ====== USER EMAIL ======= -->
        <div id="user-info-email" class="user-info">
            <p> Email: <br><%= @users.email %></p>
        </div>
        <%= link_to 'Edit Profile', edit_user_registration_path %>
    </div>

    <!-- ======= ======= ======= USER BAR REPORTS BOX ======= ======= ======= -->
    <div>
        <h2>Bar Reports</h2>
        <% @user_reports.each do |r| %>
            <div>
                <%= link_to r.bars.first.name, bar_path %> <br>       <!-- send the user to the clicked bar profile -->
                Beer: $<%= r.beer_price %>
                Wine: $<%= r.wine_price %>
                Cocktails: $<%= r.cocktails_price %>
                Rating: <%= r.rating %> <br>
                <%= r.comment %>
            </div> </br>
        <% end %>
    </div>

</div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/home.html.erb
<!-- views/admins/home.html.erb -->
<h1>Admin Home</h1>

<h3><%= link_to 'Admin Signin', new_admin_session_path %></h3> <br>
<h3><%= link_to 'Admin Signup', new_admin_registration_path %></h3>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>