config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # == Devise Routes
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }

  # == Custom routes
  root to: "users#home"
  get "/landing" => "users#landing"
  get "/users" => "users#index"
  get "/bars" => "bars#index"
  get "/neighborhoods" => "neighborhoods#index"
  get "/user_reports/:id" => "users#user_reports"
  get "/find_bar" => "bars#find_bar"
  get "/check_user/:id" => "users#check_user"

  # == Admin Routes
  get "/admin" => "admins#home"
  get "/admin_landing" => "admins#admin_landing"
  get "/admin/users/:id" => "admins#admin_user"
  get "/admin_reports" => "reports#index"

  # == Google Bars
  get "/local_bars_json" => "bars#local_bars_json"

  # == RESTful Routes
  resources :users do
      resources :reports
  end
  resources :bars
  resources :neighborhoods
  resources :photos
  resources :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
  has_many :reports

  validates :username, :uniqueness => true, :presence => { :message => "This username already exists." }

end

app/controllers/users/api_controller.rb
# ======= api_controller.rb =======
# ======= api_controller.rb =======
# ======= api_controller.rb =======

include Google_places

# ======= get_by_loc =======
def get_by_loc

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname, :username, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:fname, :lname, :username, :email, :password, :password_confirmation, :current_password])
  end

  # The path after account update
  def after_update_path_for(current_user)
      user_path(current_user)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # == GET /home
  def home
    puts "\n******** home ********"
    current_user = nil
    puts "*** current_user.inspect: #{current_user.inspect} ***"
    @users = User.all
    puts "*** current_user.inspect: #{current_user.inspect} ****"
    # puts "*** current_user[:id].inspect: #{current_user[:id].inspect} ****"
  end

  # == GET /landing
  def landing
    puts "\n******** landing ********"
    @user = User.find(current_user.id)
  end

  # GET /users
  # GET /users.json
  def index
    puts "\n******** user_index ********"
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    puts "\n******** user_show ********"
    @user = User.find(params[:id])
    @photo = Photo.where(user_id: current_user.id).first
    @user_reports = Report.where(user_id: current_user.id)
    puts "******* @user_reports: #{@user_reports.inspect}"
  end

  # ======= current user checks clicked user's profile =======
  # GET /check_user
  def check_user
      puts "\n******* check_user *******"
      @check_user = User.find(params[:id])
      @check_user_reports = Report.where(user_id: @check_user.id)
      puts "******* @check_user_reports: #{@check_user_reports.inspect}"
  end

  # GET /users/new
  def new
    puts "\n******** user_new ********"
    puts "*** @user.inspect, #{@user.inspect} ***"
    puts "*** params.inspect, #{params.inspect} ***"
    @user = User.new
    puts "@user.firstname: #{@user.firstname}"
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    puts "\n******** user_create ********"
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to '/landing', notice: 'You have successfully created an account.' }
        format.json { render :show, status: :created, location: @user }
        current_user = @user.id
      else
        format.html { redirect_to '/', notice: 'User not created' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    puts "\n******** user_delete ********"
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      puts "\n******** set_user ********"
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      puts "\n******** user_params ********"
    #   params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_menu.html.erb
<!-- ======= views/menu ======= -->

<div id="navbar">
  <a href="/"><h1 id="logo">SipSearcher</h1></a>
  <div id="nav-items">
    <% if current_user %>
        <!-- <%#= link_to 'Landing', landing_path, class: "nav-item" %> -->
        <%= link_to 'Bars', bars_path, class: "nav-item" %>
        <%= link_to 'New Bar', new_bar_path, class: "nav-item" %>
        <%= link_to 'Profile', user_path(current_user.id), class: "nav-item" %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-item" %>
        <!-- <p class="nav-item"> <%#= current_user.username %> </p> -->
    <% elsif current_admin %>
        <%= link_to 'Admin', admin_landing_path, class: "nav-item" %>
        <%= link_to 'Users', "/users", class: "nav-item" %>
        <%= link_to 'Bars', "/bars", class: "nav-item" %>
        <%= link_to 'Reports', "/admin_reports", class: "nav-item" %>
        <%= link_to 'Tags', tags_path, class: "nav-item" %>
        <%= link_to 'Locations', "/neighborhoods", class: "nav-item" %>
        <%= link_to 'Signout', destroy_admin_session_path, method: :delete, class: "nav-item" %>
    <% else %>
        <%= link_to 'Sign In', new_user_session_path, class: "nav-item" %>
        <%= link_to 'Register', new_user_registration_path, class: "nav-item" %>
    <% end %>
  </div>
</div>

app/views/users/check_user.html.erb
<!-- ====== views/users/check_user.html.erb ====== -->
<!-- ====== views/users/check_user.html.erb ====== -->

<p id="notice"><%= notice %></p>
<div id="detail-wrapper">
  <div class="profile-name-container">
    <h1 class="profile-name"><%= @check_user.username %></h1>
  </div>
  <div id="detail-container">
    <div id="left-top-area">
      <div class="form-div">
        <p id="item-display">
          <span class="item-label">First Name:</span> <span class="item"><%= @check_user.fname %></span>
        </p>
      </div>
      <div class="form-div">
        <p id="item-display">
          <span class="item-label">Last Name:</span> <span class="item"><%= @check_user.lname %></span>
        </p>
      </div>
      <div class="form-div">
        <p id="item-display">
          <span class="item-label">Email:</span> <span class="item"><%= @check_user.email %></span>
        </p>
      </div>
    </div>
    <div id="right-bottom-area">[photo]
      <!-- <%#= image_tag(@photo.id.image.url) %> -->
    </div>
  </div>
  <div id="ratings-area">
    <% @check_user_reports.each do |r| %>
      <div class="rating">
        <div class="rating-top">
          <div class="left-info">
            <div class="quarter-div">
              <span class="rating-label">Bar:</span>
              <%= link_to r.bars.first.name, bar_path(r.bars.first.id), class: "rating-bar-name" %>
            </div>
            <div class="quarter-div">
              <span class="rating-label">Rating:</span> <span class="rating-display"><%= r.rating %></span>
            </div>
          </div>
          <div class="right-info">
            <div class="report-icon-container">
              <div class="report-icon-box">
                <img src="/assets/beer.png" alt="Wine">
              </div>
              <div class="report-icon-box">
                <img src="/assets/wine.png" alt="Wine">
              </div>
              <div class="report-icon-box">
                <img src="/assets/cocktail.png" alt="Wine">
              </div>
            </div>
            <div class="report-rating-container">
              <div class="report-rating-box">
                <p class="report-rating">$<%= r.beer_price %></p>
              </div>
              <div class="report-rating-box">
                <p class="report-rating">$<%= r.wine_price %></p>
              </div>
              <div class="report-rating-box">
                <p class="report-rating">$<%= r.cocktails_price %></p>
              </div>
            </div>
          </div>
        </div>
        <div class="rating-bottom">
          <div class="rating-comment-container"><p class="rating-comment"><%= r.comment %></p></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<div id="home-wrapper">
  <div class="section" id="top-section">
    <div class="top-box">
      <div class="top">
        <img id="drinks-img" src="/assets/drinks.png" alt="Drinks">
      </div>
      <div class="bottom-phrase">Rate Drink Specials</div>
    </div>
    <div class="top-box">
      <div class="top">
        <img id="review-img" src="/assets/review.png" alt="Review">
      </div>
      <div class="bottom-phrase">Write Bar Reviews</div>
    </div>
    <div class="top-box">
      <div class="top">
      <img src="/assets/search2.png" alt="Search">
    </div>
      <div class="bottom-phrase">Search for Happy Hours</div>
    </div>
  </div>
  <div class="section" id="middle-section">
    <div class="middle-box" id="quotes-area">
      <p class="quote">"After work, I just want to know where I can enjoy affordable drinks with some friends. Luckily, there's <em>SipSearcher!"</em></p>
      <p class="signature">- Amy, Washington, DC</p>
    </div>
    <div class="middle-box" id="app-image-area">
      <img id="app-img" src="/assets/app-img.png" alt="SipSearcher">
    </div>
  </div>

  <div class="section" id="bottom-section">
    <h2 id="phrase-section">Please drink responsibly</h2>
    <a href="https://github.com/FreshOceans/SipSearcher" target="_blank"><img src="/assets/github.png" alt="Github"></a>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h2 class="header">Users</h2>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, "/admin/users/#{user.id}" %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/landing.html.erb
<div id="landing_info">
    <% if @user.fname || @user.lname != nil %>
        <h2>Welcome Back, <%= @user.fname %> <%= @user.lname %>!</h2>
        <p>Here's what's new:</p>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 class="header"><%= current_user.username %></h1>
<div id="detail-wrapper">
    <!-- No need for notice here if notice is on layouts page. -->
  <!-- <p id="notice"><%#= notice %></p> -->
  <div id="detail-container">
    <div id="left-top-area">
      <div class="form-div">
        <p id="item-display">
          <span class="item-label">First Name:</span> <span class="item"><%= current_user.fname %></span>
        </p>
      </div>
      <div class="form-div">
        <p id="item-display">
          <span class="item-label">Last Name:</span> <span class="item"><%= current_user.lname %></span>
        </p>
      </div>
      <div class="form-div">
        <p id="item-display">
          <span class="item-label">Email:</span> <span class="item"><%= current_user.email %></span>
        </p>
      </div>
      <div class="form-div">
        <%= link_to 'Edit Profile', edit_user_registration_path, class: "form-btn" %>
      </div>
    </div>
    <div id="right-bottom-area">
      <% if @photo != nil %>
          <%= image_tag(@photo.image.url) %>
      <% end %>
    </div>
    <div class="form-div">
      <p id="item-display">
        <span class="item-label">Profile Photo:</span> <span class="item"><%= link_to 'New Photo', new_photo_path, class: "nav-item" %></span>
      </p>
    </div>
  </div>
  <div id="ratings-area">
    <% @user_reports.each do |r| %>
      <div class="rating">
        <div class="rating-top">
          <div class="left-info">
            <div class="quarter-div">
              <span class="rating-label">Bar:</span>
              <%= link_to r.bars.first.name, bar_path(r.bars.first.id), class: "rating-bar-name" %>
            </div>
            <div class="quarter-div">
              <span class="rating-label">Rating:</span> <span class="rating-display"><%= r.rating %></span>
            </div>
          </div>
          <div class="right-info">
            <div class="report-icon-container">
              <div class="report-icon-box">
                <img src="/assets/beer.png" alt="Wine">
              </div>
              <div class="report-icon-box">
                <img src="/assets/wine.png" alt="Wine">
              </div>
              <div class="report-icon-box">
                <img src="/assets/cocktail.png" alt="Wine">
              </div>
            </div>
            <div class="report-rating-container">
              <div class="report-rating-box">
                <p class="report-rating">$<%= r.beer_price %></p>
              </div>
              <div class="report-rating-box">
                <p class="report-rating">$<%= r.wine_price %></p>
              </div>
              <div class="report-rating-box">
                <p class="report-rating">$<%= r.cocktails_price %></p>
              </div>
            </div>
          </div>
        </div>
        <div class="rating-bottom">
          <div class="rating-comment-container"><p class="rating-comment"><%= r.comment %></p></div>
        </div>
      </div>
    <% end %>
  </div>
</div>