config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # == Devise Routes
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }

  # == Custom routes
  root to: "users#home"
  get "/landing" => "users#landing"
  get "/users" => "users#index"
  get "/bars" => "bars#index"
  get "/neighborhoods" => "neighborhoods#index"
  get "/user_reports/:id" => "users#user_reports"
  get "/find_bar" => "bars#find_bar"
  get "/check_user/:id" => "users#check_user"

  # == Admin Routes
  get "/admin" => "admins#home"
  get "/admin_landing" => "admins#admin_landing"
  get "/admin/users/:id" => "admins#admin_user"
  get "/admin_reports" => "reports#index"

  # == Google Bars
  get "/local_bars_json" => "bars#local_bars_json"

  # == RESTful Routes
  resources :users do
      resources :reports
  end
  resources :bars
  resources :neighborhoods
  resources :photos
  resources :tags
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  has_many :bar_reports
  has_many :bars, through: :bar_reports, dependent: :destroy
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    puts "\n******** reports_index ********"
    @reports = Report.all
    @user = User.all
    @bars = Bar.all
    puts "******** @user.inspect: #{@user.inspect} ********"
    puts "******** @bar.inspect: #{@bar.inspect} ********"
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    puts "\n******** reports_show ********"
    @report = Report.all
  end

  # GET /reports/new
  def new
    puts "\n******** reports_new ********"
    @user = User.find(current_user.id)
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
    puts "\n******** reports_edit ********"
  end

  # POST /reports
  # POST /reports.json
  def create
     puts "\n******** reports_create ********"
     puts "report_params: #{report_params.inspect}"

     new_params = report_params
     new_params[:user_id] = current_user.id
     puts "new_params: #{new_params.inspect}"

    @report = Report.new(new_params)
     puts "@report: #{@report}"

    respond_to do |format|
       if @report.save
           puts "==++ create report SAVED ++=="
           @report = Report.order("created_at").last
           puts "@report[:id]: #{@report[:id]}"
           puts "session[:bar_id]: #{session[:bar_id].inspect}"
           @bar_report = BarReport.create(bar_id:session[:bar_id], report_id:@report[:id] )
           format.html { redirect_to bar_path(session[:bar_id]), notice: 'Report was successfully created.' }
           format.json { render :show, status: :created, location: @report }
       else
           puts "==++ create report FAILED ++=="
         # format.html { render :new }
         format.html { redirect_to '/', notice: 'Report was not created.' }
         format.json { render json: @report.errors, status: :unprocessable_entity }
       end
     end
   end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
      puts "\n******** reports_update ********"
      new_params = report_params
      new_params[:user_id] = current_user.id
      respond_to do |format|
        if @report.update(new_params)
          format.html { redirect_to @report, notice: 'Report was successfully updated.' }
          format.json { render :show, status: :ok, location: @report }
        else
          format.html { render :edit }
          format.json { render json: @report.errors, status: :unprocessable_entity }
        end
      end
   end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    puts "\n******** reports_delete ********"
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      puts "\n******** set_reports ********"
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      puts "\n******** reports_params ********"
      params.require(:report).permit(:user_id, :beer_price, :wine_price, :cocktails_price, :rating, :comment )
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<% puts "++== before  @report.inspect #{@report.inspect} ++==" %>
<%= form_for([@user, @report]) do |form| %>
<% puts "++== after @report.inspect #{@report.inspect} ++==" %>

  <div id="rating-form">
    <div class="rating-form-top">
      <div class="rating-form-left-info">
        <div id="new-rating-header">Add a New Report!</div>
        <div id="rating-form-rating-select">
          <% rating_score = [ [ "1", 1, {class: 'rating-option'} ], [ "2", 2, {class: 'rating-option'} ], [ "3", 3, {class: 'rating-option'} ], [ "4", 4, {class: 'rating-option'} ], [ "5", 5, {class: 'rating-option'} ] ] %>
          <%= select("report", :rating, options_for_select(rating_score), id: "rating-drop-down", class: "data-value")%>
        </div>
      </div>
      <div class="rating-form-right-info">
        <div class="rating-form-icon-container">
          <div class="rating-form-icon-box">
            <img src="/assets/beer.png" alt="Wine">
          </div>
          <div class="rating-form-icon-box">
            <img src="/assets/wine.png" alt="Wine">
          </div>
          <div class="rating-form-icon-box">
            <img src="/assets/cocktail.png" alt="Wine">
          </div>
        </div>
        <div class="rating-form-rating-container">
            <% drink_prices = [[ "$3-5", 4, {class: 'rating-option'} ], [ "$5-7", 6, {class: 'rating-option'} ],[ "$7-9", 8, {class: 'rating-option'} ]] %>
            <div class="rating-form-rating-box">
                <%= select("report", :beer_price, options_for_select(drink_prices), id: "beer-drop-down")%>
            </div>
            <div class="rating-form-rating-box">
                <%= select("report", :wine_price, options_for_select(drink_prices), id: "wine-drop-down")%>
            </div>
            <div class="rating-form-rating-box">
                <%= select("report", :cocktails_price, options_for_select(drink_prices), id: "cocktail-drop-down")%>
            </div>
        </div>
      </div>
    </div>
    <div class="rating-form-bottom">
      <textarea id="comment" class="rating-form-comment-area" name="report[comment]" maxlength="150" rows="8" cols="80" placeholder="What did you think about this happy hour?"></textarea>
      <%= form.submit "Submit", class: "submit_btn" %>
    </div>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to @bars.name, user_report_path(@user, report.id) %></td>
        <td><%#= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Delete', user_report_path(@user, report.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%#= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<!-- ======= views/reports/show.html.erb ======= -->

<p id="notice"><%= notice %></p>